/** Executes program-model deterministically and produces serializable runtime results. */
export const PACKAGE_NAME = "@agorix/runtime";

export {
  DEFAULT_EXECUTION_BUDGET,
  runProgram,
  type ExecutionBoundary,
  toSanitizedTutorContext,
  type ExecutionOptions,
  type ExecutionTraceEntry,
  type RunOutcome,
  type RunResult,
  type RuntimeObservation,
  type RuntimeObservationKind,
  type SanitizedTutorContext,
} from "./execute.js";
export {
  runMultiActorProgram,
  type MultiActorExecutionOptions,
  type MultiActorFrame,
  type MultiActorRunResult,
  type MultiActorRuntimeActor,
  type MultiActorScriptActivation,
  type MultiActorTraceEntry,
  type RuntimeEvent,
} from "./multiActor.js";
export { RuntimeExecutionError } from "./errors.js";
export {
  assertAllowedRuntimeOperation,
  assertProgramOperationsAllowed,
  isAllowedRuntimeOperation,
  listRuntimeOperations,
  RUNTIME_EXPRESSION_OPERATIONS,
  RUNTIME_OPERATIONS,
  RUNTIME_STATEMENT_OPERATIONS,
  RUNTIME_TRIGGER_OPERATIONS,
  type RuntimeOperation,
  type RuntimeOperationAllowlistIsExhaustive,
  type RuntimeOperationKind,
} from "./operations.js";
export {
  cloneWorldState,
  changeVariableWorld,
  createWorldState,
  getVariableWorld,
  hideWorld,
  moveWorld,
  normalizeCoordinate,
  normalizeHeading,
  resetWorldState,
  sayWorld,
  setVariableVisibilityWorld,
  setVariableWorld,
  setSpriteSizeWorld,
  showWorld,
  switchBackdropWorld,
  switchCostumeWorld,
  thinkWorld,
  touchingGoal,
  turnWorld,
  type LooksBubble,
  type Position,
  type SpriteState,
  type VariableState,
  type WorldState,
  type WorldStateInput,
} from "./world.js";
