/** Versioned project storage abstraction; web starts with browser-local persistence. */
export {
  PACKAGE_NAME,
  PersistenceError,
  type PersistenceErrorCode,
  type StoredProject,
  type ProjectMetadata,
  type BrowserStorageAdapter,
  type MigrationFn,
  type MigrationStep,
  BrowserLocalStorageAdapter,
  ProjectStore,
} from "./store.js";
export {
  ACTOR_COORDINATE_LIMIT,
  ACTOR_MAX_COUNT,
  ACTOR_NAME_MAX_LENGTH,
  ACTOR_SIZE_MAX,
  ACTOR_SIZE_MIN,
  validateProjectActors,
  type ProjectActor,
  type ProjectActors,
} from "./actors.js";
export {
  CROSS_SURFACE_CONTRACT_VERSION,
  FORBIDDEN_CANONICAL_IDENTITY_KEYS,
  FORBIDDEN_CANONICAL_PROGRAM_KEYS,
  FORBIDDEN_CANONICAL_UI_KEYS,
  assertCrossSurfaceCompatibleProject,
  assertNoUiSpecificProgramState,
  assertSemanticallyEquivalentProjects,
  semanticProjectHash,
  semanticProjectSnapshot,
  type SemanticProjectSnapshot,
} from "./compatibility.js";
export {
  AGORIX_PROJECT_EXTENSION,
  AGORIX_PROJECT_FORMAT,
  AGORIX_PROJECT_FORMAT_VERSION,
  AGORIX_PROJECT_MAX_BYTES,
  AGORIX_PROJECT_MEDIA_TYPE,
  FORBIDDEN_PORTABLE_PROJECT_KEYS,
  parseAgorixProject,
  sanitizeAgorixFilename,
  serializeAgorixProject,
  validateAgorixProjectEnvelope,
  validatePortableStoredProject,
  type AgorixProjectEnvelopeV1,
  type AgorixProjectSource,
  type ParseAgorixProjectOptions,
  type SerializeAgorixProjectOptions,
} from "./portable.js";
